import type { Metadata } from "next";
import "./globals.css";
import Navbar from "@/src/components/common/Navbar/Navbar";
import Footer from "@/src/components/common/Footer/Footer";
import CTA from "@/src/components/common/CTA/CTA";

export const metadata: Metadata = {
  title: "AP2L",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <Navbar />
        <main>{children}</main>
        <CTA />
        <Footer />
      </body>
    </html>
  );
}
